version = 1

exclude_patterns = [
    "/dist",
    "/test"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser"]
  plugins = ["vue"]
  style_guide = "standard"
  dialect = "typescript"
